vich_uploader:
    db_driver: orm

    # prise en charge de php 8
    metadata:
        type: attribute
    mappings:
       home:
           uri_prefix: /images/home
           upload_destination: '%kernel.project_dir%/public/images/home'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
       carousel:
           uri_prefix: /images/carousel
           upload_destination: '%kernel.project_dir%/public/images/carousel'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       categorie:
           uri_prefix: /images/categorie
           upload_destination: '%kernel.project_dir%/public/images/categorie'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       produit:
           uri_prefix: /images/produit
           upload_destination: '%kernel.project_dir%/public/images/produit'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       article:
           uri_prefix: /images/article
           upload_destination: '%kernel.project_dir%/public/images/article'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       avatar:
           uri_prefix: /images/avatar
           upload_destination: '%kernel.project_dir%/public/images/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       

